#pragma once

#include "vmulticommon.h"
//터치 액션
#define VS_TOUCH_FLAG_NONE		0
#define VS_TOUCH_FLAG_BEGIN		1		
#define VS_TOUCH_FLAG_MOVE		2
#define VS_TOUCH_FLAG_END		3
#define VS_TOUCH_FLAG_CANCELED	4

//디바이스 모드
#define VS_MODE_NONE					0
#define VS_MODE_TOUCHSCREEN				1
#define VS_MODE_MOUSE					2
#define VS_MODE_KEYBOARD				3
#define VS_MODE_STYLUS_PEN				4
#define VS_MODE_JOYSTIC					5

//스크린 모드
#define VS_SCREEN_MODE_NONE						0
#define VS_SCREEN_MODE_POWERPOINT				1
#define VS_SCREEN_MODE_POWERPOINT_SLIDESHOW		2

//버튼 타입
#define VS_BUTTON_NONE							0
#define VS_BUTTON_WINDOWS						1
#define VS_BUTTON_NAVIGATION					2
#define VS_BUTTON_OPEN_SLIDESHOW_FIRST_PAGE		3
#define VS_BUTTON_OPEN_SLIDESHOW_CURRENT_PAGE	4
#define VS_BUTTON_CLOSE_SLIDESHOW				5
#define VS_BUTTON_PREVIOUS_SLIDE				6
#define VS_BUTTON_NEXT_SLIDE					7
#define VS_BUTTON_SHOW_POINTER					8
#define VS_BUTTON_BALLPOINT_PEN					9
#define VS_BUTTON_INK_PEN						10
#define VS_BUTTON_HIGHLIGHTER					11
#define VS_BUTTON_INK_TOGGLE					12
#define VS_BUTTON_ERASER						13
#define VS_BUTTON_PAGE_ERAGER					14

//패킷 타입
#define VS_SOCKET_PACKET_HEADER			83567837
#define VS_SOCKET_PACKET_FOOTER			73876538
#define VS_SOCKET_PACKET_BROADCAST			0
#define VS_SOCKET_PACKET_COORDINATES		1
#define VS_SOCKET_PACKET_AUTEHNTICATION		2
#define VS_SOCKET_PACKET_REQUEST_IMAGE		3
#define VS_SOCKET_PACKET_CHANGE_MODE		4
#define VS_SOCKET_PACKET_VIRTUAL_BUTTON		5
#define VS_SOCKET_PACKET_AUTO_CONNECT		6
#define VS_SOCKET_PACKET_CHECK_CONNECTION	7
#define VS_SOCKET_PACKET_INPUT_KEYBOARD		8
#define VS_SOCKET_PACKET_UNKNOWN			-1

#define VS_SOCKET_PACKET_TEMPLATE_CNT		3
#define VS_SOCKET_PACKET_BROADCAST_CNT		1
#define VS_SOCKET_PACKET_COORDINATES_CNT	30
#define VS_SOCKET_PACKET_KEYINPUTS_INT_CNT	10
#define VS_SOCKET_PACKET_KEYINPUTS_BYTE_CNT	7

#define MSG_VALID 1000
#define MSG_INVALID_PARAMETER_CNT -1

typedef struct WOW_TOUCH_INFO {
	INT os;
	INT id[5];
	INT action[5];
	POINT position[5];
	POINT resolution;
	INT contactCnt;
	DWORD tick;
} WOW_TOUCH_INFO, *PWOW_TOUCH_INFO;

typedef struct WOW_MOUSE_INFO {
	INT os;
	INT id[5];
	INT action[5];
	POINT position[5];
	POINT resolution;
	INT contactCnt;
	BOOL bBeginOrMove;
	BOOL bHWheelMode;
	BOOL bVWheelMode;
	BOOL bExtendButton;
	DWORD tick;
} WOW_MOUSE_INFO, *PWOW_MOUSE_INFO;

typedef struct WOW_KEYBOARD_INFO {
	BYTE shiftKeys;
    BYTE keyCodes[KBD_KEY_CODES];
	INT imeKey;
	UINT delayMilliseconds;
} WOW_KEYBOARD_INFO, *PWOW_KEYBOARD_INFO;